---
parser: babel-eslint

extends: eslint-config-shakacode

plugins:
  - react
  - jest

globals:
  __DEBUG_SERVER_ERRORS__: true
  __SERVER_ERRORS__: true

env:
  browser: true
  node: true
  mocha: true
  jest/globals: true

rules:
  import/extensions: [2, { js: "never", jsx: "never" }]
  function-paren-newline: ["error", "consistent"]

  # Good idea, but let's go to flow before fixing all these
  react/forbid-prop-types: 0
  jsx-a11y/href-no-hash: 0

  jsx-a11y/anchor-is-valid: off

#  arrow-parens:
#    - 0
#    - "as-needed"

settings:
  import/resolver:
    webpack:
      config: 'webpack.client.base.config.js'
