#!/bin/sh

SCRIPT_PATH=$(dirname $(realpath $0))
export $(cat $SCRIPT_PATH/env_defaults | grep "^[^#]" | xargs)

IMAGE=$CPLN_GVC:latest

for arg in "$@"; do
  TEMPLATE="$SCRIPT_PATH/templates/$arg.yaml"

  if [ -f "$TEMPLATE" ]; then
    cat "$TEMPLATE" |
      sed "s/APP_GVC/$CPLN_GVC/" |
      sed "s/APP_LOCATION/$CPLN_LOCATION/" |
      sed "s/APP_ORG/$CPLN_ORG/" |
      sed "s/APP_IMAGE/$IMAGE/" |
      cpln apply --gvc $CPLN_GVC --file -
  else
    echo "Can't find template for '$arg' at $TEMPLATE"
    exit -1
  fi
done
