# Control Plane GitHub Action

name: Deploy to Control Plane
description: 'Deploys an application to Control Plane'

inputs:
  app_name:
    description: 'Name of the application'
    required: true
  org:
    description: 'Organization name'
    required: true
  wait_timeout:
    description: 'Timeout in seconds for waiting for workloads to be ready'
    required: false
    default: '900'
  pr_number:
    description: 'Pull Request number'
    required: true

outputs:
  review_app_url:
    description: 'URL of the deployed application'
    value: ${{ steps.deploy.outputs.review_app_url }}

runs:
  using: "composite"
  steps:
    - name: Deploy to Control Plane
      id: deploy
      shell: bash
      env:
        APP_NAME: ${{ inputs.app_name }}
        CPLN_ORG: ${{ inputs.org }}
        WAIT_TIMEOUT: ${{ inputs.wait_timeout }}
      run: |
        # Run the deployment script
        if ! ${{ github.action_path }}/scripts/deploy.sh; then
          exit 1
        fi
