# Control Plane GitHub Action

name: 'Setup Environment'
description: 'Sets up Ruby, installs Control Plane CLI, cpflow gem, and sets up the default profile'

inputs:
  token:
    description: 'Control Plane token'
    required: true
  org:
    description: 'Control Plane organization'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.4'

    - name: Install Control Plane CLI and cpflow gem
      shell: bash
      run: |
        sudo npm install -g @controlplane/cli@3.3.0
        cpln --version
        gem install cpflow -v 4.1.0
        cpflow --version

    - name: Setup Control Plane Profile
      shell: bash
      run: |
        TOKEN="${{ inputs.token }}"
        ORG="${{ inputs.org }}"
        
        if [ -z "$TOKEN" ]; then
          echo " Error: Control Plane token not provided"
          exit 1
        fi
        
        if [ -z "$ORG" ]; then
          echo " Error: Control Plane organization not provided"
          exit 1
        fi
        
        echo "Setting up Control Plane profile..."
        echo "Organization: $ORG"
        cpln profile update default --org "$ORG" --token "$TOKEN"
        
        echo "Setting up Docker login for Control Plane registry..."
        cpln image docker-login --org "$ORG"
