# Control Plane GitHub Action

name: 'Setup Environment'
description: 'Sets up Ruby, installs Control Plane CLI, cpflow gem, and sets up the default profile'

runs:
  using: 'composite'
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.4'

    - name: Install Control Plane CLI and cpflow gem
      shell: bash
      run: |
        sudo npm install -g @controlplane/cli@3.3.0
        cpln --version
        gem install cpflow -v 4.1.0
        cpflow --version

    - name: Setup Control Plane Profile
      shell: bash
      env:
        CPLN_TOKEN: ${{ env.CPLN_TOKEN }}
        CPLN_ORG: ${{ env.CPLN_ORG }}
      run: |
        if [ -z "$CPLN_TOKEN" ]; then
          echo " Error: CPLN_TOKEN environment variable is not set"
          exit 1
        fi
        
        if [ -z "$CPLN_ORG" ]; then
          echo " Error: CPLN_ORG environment variable is not set"
          exit 1
        fi
        
        echo "Setting up Control Plane profile..."
        echo "Organization: $CPLN_ORG"
        cpln profile update default --org "$CPLN_ORG" --token "$CPLN_TOKEN"
        
        echo "Setting up Docker login for Control Plane registry..."
        cpln image docker-login --org "$CPLN_ORG"
