name: Build Docker Image
description: 'Builds a Docker image for the application'

inputs:
  app_name:
    description: 'Name of the application'
    required: true
  org:
    description: 'Organization name'
    required: true
  commit:
    description: 'Commit SHA to tag the image with'
    required: true
  PR_NUMBER:
    description: 'PR number'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      id: build
      shell: bash
      run: |
        echo "🏗️ Building Docker image for PR #${PR_NUMBER} (commit ${{ inputs.commit }})..."
        
        if cpflow build-image -a "${{ inputs.app_name }}" --commit="${{ inputs.commit }}" --org="${{ inputs.org }}"; then
          echo "✅ Docker image build successful for PR #${PR_NUMBER} (commit ${{ inputs.commit }})"
        else
          echo "❌ Docker image build failed for PR #${PR_NUMBER} (commit ${{ inputs.commit }})"
          exit 1
        fi
