name: Cleanup Stale Review Apps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  cleanup:
    uses: shakacode/control-plane-flow/.github/workflows/cpflow-cleanup-stale-review-apps.yml@cfe494bf32925d49508380e03856d97bd71f6689
    with:
      control_plane_flow_ref: cfe494bf32925d49508380e03856d97bd71f6689
    secrets: inherit
