name: Promote Staging to Production

on:
  workflow_dispatch:
    inputs:
      confirm_promotion:
        description: Type "promote" to confirm promotion of staging to production
        required: true
        type: string

permissions:
  contents: write

jobs:
  promote-to-production:
    if: github.event.inputs.confirm_promotion == 'promote'
    uses: shakacode/control-plane-flow/.github/workflows/cpflow-promote-staging-to-production.yml@6f44c84049d4fa09aaa8c0a72cc436cd52e66fb0
    with:
      control_plane_flow_ref: 6f44c84049d4fa09aaa8c0a72cc436cd52e66fb0
    secrets: inherit
