name: "JS CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [22.x]
        ruby: [3.3.4]

    env:
      RAILS_ENV: test
      NODE_ENV: test
      USE_COVERALLS: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: |
          bundle install
          yarn install --frozen-lockfile --non-interactive --prefer-offline

      - name: Build i18n libraries
        run: bundle exec rake react_on_rails:locale

      - name: Generate React on Rails packs
        run: bundle exec rails react_on_rails:generate_packs

      - name: Run js tests
        run: bundle exec rake ci:js
