name: "Rspec CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [22.x]
        ruby: [3.4.6]

    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    env:
      RAILS_ENV: test
      NODE_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      DRIVER: selenium_chrome
      CHROME_BIN: /usr/bin/google-chrome
      USE_COVERALLS: true

    steps:
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Check Chrome version
        run: chrome --version

      - name: Check Chrome version
        run: google-chrome --version

      - name: Set Display environment variable
        run: "export DISPLAY=:99"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: |
          bundle install
          yarn install --frozen-lockfile --non-interactive --prefer-offline

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Build i18n libraries
        run: bundle exec rake react_on_rails:locale

      - name: Generate React on Rails packs
        run: bundle exec rails react_on_rails:generate_packs

      - name: Build Rescript components
        run: yarn res:build

      - name: Build shakapacker chunks
        run: NODE_ENV=development bundle exec bin/shakapacker

      - name: Run rspec with xvfb
        uses: coactions/setup-xvfb@v1
        with:
          run: bundle exec rake ci:rspec
          working-directory: ./ #optional
          options: ":99 -ac -screen scn 1600x1200x16"
